/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const IceCreamFlavorInput = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const IceCreamFlavor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OrderItem = IDL.Record({
  'flavorId' : IDL.Nat,
  'flavorName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'razorpayPaymentId' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'deliveryAddress' : IDL.Text,
  'customerPhone' : IDL.Text,
  'razorpayOrderId' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const IceCreamFlavorUpdate = IDL.Record({
  'name' : IDL.Opt(IDL.Text),
  'isAvailable' : IDL.Opt(IDL.Bool),
  'description' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'isFeatured' : IDL.Opt(IDL.Bool),
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFlavor' : IDL.Func([IceCreamFlavorInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContactMessage' : IDL.Func([Time], [], []),
  'clearAllFlavors' : IDL.Func([], [], []),
  'deleteFlavor' : IDL.Func([IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllFlavors' : IDL.Func([], [IDL.Vec(IceCreamFlavor)], ['query']),
  'getAvailableFlavors' : IDL.Func([], [IDL.Vec(IceCreamFlavor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedFlavors' : IDL.Func([], [IDL.Vec(IceCreamFlavor)], ['query']),
  'getFlavor' : IDL.Func([IDL.Nat], [IceCreamFlavor], ['query']),
  'getFlavorsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IceCreamFlavor)],
      ['query'],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUpiId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchFlavors' : IDL.Func([IDL.Text], [IDL.Vec(IceCreamFlavor)], ['query']),
  'seedDefaultFlavors' : IDL.Func([], [IDL.Nat], []),
  'setRazorpayKeyId' : IDL.Func([IDL.Text], [], []),
  'setUpiId' : IDL.Func([IDL.Text], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'toggleAvailability' : IDL.Func([IDL.Nat], [], []),
  'toggleFeatured' : IDL.Func([IDL.Nat], [], []),
  'updateFlavor' : IDL.Func([IDL.Nat, IceCreamFlavorUpdate], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const IceCreamFlavorInput = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const IceCreamFlavor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OrderItem = IDL.Record({
    'flavorId' : IDL.Nat,
    'flavorName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'razorpayPaymentId' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'deliveryAddress' : IDL.Text,
    'customerPhone' : IDL.Text,
    'razorpayOrderId' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const IceCreamFlavorUpdate = IDL.Record({
    'name' : IDL.Opt(IDL.Text),
    'isAvailable' : IDL.Opt(IDL.Bool),
    'description' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'isFeatured' : IDL.Opt(IDL.Bool),
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFlavor' : IDL.Func([IceCreamFlavorInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContactMessage' : IDL.Func([Time], [], []),
    'clearAllFlavors' : IDL.Func([], [], []),
    'deleteFlavor' : IDL.Func([IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllFlavors' : IDL.Func([], [IDL.Vec(IceCreamFlavor)], ['query']),
    'getAvailableFlavors' : IDL.Func([], [IDL.Vec(IceCreamFlavor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedFlavors' : IDL.Func([], [IDL.Vec(IceCreamFlavor)], ['query']),
    'getFlavor' : IDL.Func([IDL.Nat], [IceCreamFlavor], ['query']),
    'getFlavorsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IceCreamFlavor)],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getRazorpayKeyId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUpiId' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchFlavors' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IceCreamFlavor)],
        ['query'],
      ),
    'seedDefaultFlavors' : IDL.Func([], [IDL.Nat], []),
    'setRazorpayKeyId' : IDL.Func([IDL.Text], [], []),
    'setUpiId' : IDL.Func([IDL.Text], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'toggleAvailability' : IDL.Func([IDL.Nat], [], []),
    'toggleFeatured' : IDL.Func([IDL.Nat], [], []),
    'updateFlavor' : IDL.Func([IDL.Nat, IceCreamFlavorUpdate], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };