/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface IceCreamFlavor {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : [] | [string],
  'isFeatured' : boolean,
  'category' : string,
  'price' : number,
}
export interface IceCreamFlavorInput {
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : [] | [string],
  'isFeatured' : boolean,
  'category' : string,
  'price' : number,
}
export interface IceCreamFlavorUpdate {
  'name' : [] | [string],
  'isAvailable' : [] | [boolean],
  'description' : [] | [string],
  'imageUrl' : [] | [string],
  'isFeatured' : [] | [boolean],
  'category' : [] | [string],
  'price' : [] | [number],
}
export interface Order {
  'id' : bigint,
  'razorpayPaymentId' : string,
  'customerName' : string,
  'status' : string,
  'deliveryAddress' : string,
  'customerPhone' : string,
  'razorpayOrderId' : string,
  'totalAmount' : number,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'flavorId' : bigint,
  'flavorName' : string,
  'quantity' : bigint,
  'price' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFlavor' : ActorMethod<[IceCreamFlavorInput], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactMessage' : ActorMethod<[Time], undefined>,
  'clearAllFlavors' : ActorMethod<[], undefined>,
  'deleteFlavor' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllFlavors' : ActorMethod<[], Array<IceCreamFlavor>>,
  'getAvailableFlavors' : ActorMethod<[], Array<IceCreamFlavor>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedFlavors' : ActorMethod<[], Array<IceCreamFlavor>>,
  'getFlavor' : ActorMethod<[bigint], IceCreamFlavor>,
  'getFlavorsByCategory' : ActorMethod<[string], Array<IceCreamFlavor>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getRazorpayKeyId' : ActorMethod<[], [] | [string]>,
  'getUpiId' : ActorMethod<[], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [string, string, string, Array<OrderItem>, number, string, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchFlavors' : ActorMethod<[string], Array<IceCreamFlavor>>,
  'seedDefaultFlavors' : ActorMethod<[], bigint>,
  'setRazorpayKeyId' : ActorMethod<[string], undefined>,
  'setUpiId' : ActorMethod<[string], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'toggleAvailability' : ActorMethod<[bigint], undefined>,
  'toggleFeatured' : ActorMethod<[bigint], undefined>,
  'updateFlavor' : ActorMethod<[bigint, IceCreamFlavorUpdate], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];